name: Java CI with Maven and Docker - Developer Lakshmi Narayanan T

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code
    - name: Set up JDK 7
      uses: actions/setup-java@v3
      with:
        java-version: '7'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and push Docker Push
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: lakshmanan6991/githubaction
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
